@startuml
!include https://raw.githubusercontent.com/bschwarz/puml-themes/master/themes/bluegray/puml-theme-bluegray.puml
participant operator <<local machine>>
participant "AWS\nKMS" as kms <<server>>
participant "git\nserver" as git <<server>>
participant "CI/CD\ntooling" as cicd <<server>>
participant "execution\nenvironment" as exe <<server>>

operator->operator: install sops
operator->operator: sops: encrypt plain text file
activate operator

operator->kms: sops: use KMS key for encryption
kms->operator: sops: encrypted file
operator->operator: encrypted file

deactivate operator

operator->git: commit encrypted file
git-->cicd: trigger
cicd->git: checkout file
git->cicd: encrypted file
cicd->exe: encrypted file

exe->exe: install sops
exe->exe: sops: encrypt plain text file
activate exe

exe->kms: sops: use KMS key for decryption
kms->exe: sops: decrypted file
exe->exe: decrypted file

deactivate exe

exe -> exe: set secrete as env var.
@enduml
