@startuml
actor operator
participant "Mozilla\nSOPS" as sops
participant "AWS\nKMS" as kms
participant git
participant "CI/CD\ntooling" as cicd
participant "execution\nenvironment" as exe

operator->sops: encrypt plain text file
sops->kms: use KMS key for encryption
kms->sops: encrypted file
sops->operator: encrypted file


exe->exe: install sops


operator->git: commit encrypted file
git-->cicd: trigger
cicd->git: checkout file
git->cicd: encrypted file
cicd->exe: encrypted file


exe -> exe: decrypt file and set env vars
@enduml
